# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Deploy Para Hostinger
        uses: ssh root@89.117.32.249
        with:
          args: "cd /controle-de-estoque && git pull origin dev"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      